# Generated by Django 3.1.8 on 2023-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230505_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default=254710192336, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='first_two_names',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('1', 'Mombasa'), ('2', 'Nairobi'), ('3', 'Kisumu'), ('4', 'Nakuru'), ('5', 'Namanga'), ('6', 'Kilifi'), ('7', 'Kwale'), ('8', 'Eldoret'), ('9', 'Moyale'), ('10', 'Busia')], default='Nairobi', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
