# Generated by Django 3.1.8 on 2023-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230506_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='Nairobi', max_length=50),
        ),
    ]
