# Generated by Django 3.1.8 on 2023-05-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230506_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='resume',
        ),
    ]
