# Generated by Django 3.1.8 on 2023-05-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230506_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default='1112223', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_two_names',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=150),
        ),
    ]
