# Generated by Django 3.1.8 on 2023-05-09 14:25

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='Kenya Bureau of Standards - KEBS', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Contract', 'Contract Time'), ('Internship', 'Internship'), ('Industrial Attachment', 'Industrial Attachment')], default='Full Time', max_length=50, null=True)),
                ('description', models.TextField()),
                ('qualifications_req', models.CharField(max_length=1000, null=True)),
                ('experience_level', models.CharField(choices=[('ENTRY-LEVEL', 'ENTRY-LEVEL'), ('INTERMEDIATE-LEVEL', 'INTERMEDIATE-LEVEL'), ('MID-LEVEL', 'MID-LEVEL'), ('SENIOR OR EXECUTIVE-LEVEL', 'SENIOR OR EXECUTIVE-LEVEL')], default='MID-LEVEL', max_length=30)),
                ('remuneration', models.CharField(default='N/A', max_length=50)),
                ('location', models.CharField(choices=[('1', 'Mombasa'), ('2', 'Nairobi'), ('3', 'Kisumu'), ('4', 'Nakuru'), ('5', 'Namanga'), ('6', 'Kilifi'), ('7', 'Kwale'), ('8', 'Eldoret'), ('9', 'Moyale'), ('10', 'Busia')], default='Nairobi', max_length=20)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title')),
                ('staff', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='unique_applicant_job_match'),
        ),
    ]
